### ISSUE TITLE
Project: Triage

### ISSUE THREAD

**Issue by noahadler** [UK-AS-HIVE/meta-meteor#1]
Help queue to replace waggle

**Comment by noahadler** [comment]
We have MVP stories written down in the planning document.  Let's start getting them implemented, and check them off once we have a passing test for each one, using either nightwatch or mocha/chai-webbrowser.  The former works more reliably in my experience so far.

**Comment by mpaddock** [comment]
Questions to be addressed at next planning session:

-How are black box fields going to be handled from a UX standpoint? 
-How is queue membership determined? (SGs / set within the app)?

**Comment by mpaddock** [comment]
Even if queue membership is handled by SG, where/how are queues defined?
